Repository jaypeasee/national-parkfinder, pull requests merged in 2021-01, with the labels that each got.

#16 Feature/display parks
  .eslintcache
  package-lock.json
  package.json
  src/App/App.tsx
  src/Banner/Banner.tsx
  src/MainNav/MainNav.scss
  src/MainNav/MainNav.tsx
  src/ParkBtn/ParkBtn.scss
  src/ParkBtn/ParkBtn.tsx
  src/ParkContainer/ParkContainer.tsx
  src/ParkContainer/interfaces.tsx
  src/ParkContainer/npsApiCall.js
  src/ParkData.js
  src/ParkInfo/ParkInfo.tsx
  src/ParkList/ParkList.scss
  src/ParkList/ParkList.tsx
  src/index.js
Labels: feature

#38 Feature/router park info
  .eslintcache
  package-lock.json
  package.json
  src/App/App.tsx
  src/MainNav/MainNav.tsx
  src/NavSearch/NavSearch.tsx
  src/ParkBtn/ParkBtn.tsx
  src/ParkContainer/ParkContainer.tsx
  src/ParkInfo/ParkInfo.tsx
  src/ParkList/ParkList.tsx
  src/SavedParks/SavedParks.tsx
  src/UserNav/UserNav.tsx
  src/index.js
  src/interfaces.tsx
Labels: feature

#42 Feature/park info
  .eslintcache
  .vscode/settings.json
  package-lock.json
  package.json
  src/About/About.tsx
  src/App/App.tsx
  src/Banner/Banner.tsx
  src/Contact/Contact.tsx
  src/Location/Location.tsx
  src/MainNav/MainNav.tsx
  src/NavSearch/NavSearch.tsx
  src/ParkContainer/ParkContainer.tsx
  src/ParkContainer/npsApiCall.js
  src/ParkInfo/ParkInfo.tsx
  src/ParkList/ParkList.tsx
  src/interfaces.tsx
Labels: enhancement, feature

#43 Feature/user view
  .eslintcache
  src/About/About.scss
  src/About/About.tsx
  src/App/App.scss
  src/App/App.tsx
  src/Banner/Banner.scss
  src/Banner/Banner.tsx
  src/BannerIcons/BannerIcons.scss
  src/BannerIcons/BannerIcons.tsx
  src/Contact/Contact.tsx
  src/Footer/Footer.scss
  src/Footer/Footer.test.js
  src/Footer/Footer.tsx
  src/Location/Location.scss
  src/Location/Location.tsx
  src/MainNav/MainNav.scss
  src/MainNav/MainNav.tsx
  src/NavSearch/NavSearch.scss
  src/NavSearch/NavSearch.tsx
  src/ParkBtn/ParkBtn.tsx
  src/ParkContainer/ParkContainer.scss
  src/ParkContainer/ParkContainer.tsx
  src/ParkContainer/npsApiCall.js
  src/ParkData.js
  src/ParkInfo/ParkInfo.scss
  src/ParkInfo/ParkInfo.tsx
  src/ParkList/ParkList.scss
  src/ParkList/ParkList.tsx
  src/SavedCard/SavedCard.scss
  src/SavedCard/SavedCard.tsx
  src/SavedParks/SavedParks.tsx
  src/UserNav/UserNav.scss
  src/UserNav/UserNav.tsx
  src/index.js
  src/interfaces.tsx
  src/mixins.scss
  src/variables.scss
Labels: busy work, feature, refactor

#44 TDD - Main Nav
  .eslintcache
  src/MainNav/MainNav.test.js
  src/NavSearch/NavSearch.test.js
  src/ParkBtn/ParkBtn.test.js
  src/ParkBtn/ParkBtn.tsx
  src/ParkList/ParkList.test.js
  src/ParkList/ParkList.tsx
Labels: TDD

#48 Tdd/park container
  .eslintcache
  package-lock.json
  package.json
  src/App/App.test.js
  src/Banner/Banner.test.js
  src/Banner/Banner.tsx
  src/BannerIcons/BannerIcons.test.js
  src/BannerIcons/BannerIcons.tsx
  src/Footer/Footer.test.js
  src/SavedCard/SavedCard.tsx
  src/SavedParks/SavedParks.test.js
  src/SearchSaved/SearchSaved.scss
  src/SearchSaved/SearchSaved.test.js
  src/SearchSaved/SearchSaved.tsx
  src/UserNav/UserNav.test.js
Labels: TDD

#49 Tdd/park info
  src/About/About.test.js
  src/Contact/Contact.test.js
  src/Location/Location.test.js
  src/ParkInfo/ParkInfo.test.js
  src/SavedCard/SavedCard.test.js
  src/samplePark.js
Labels: TDD

#52 Tdd/integrations
  .eslintcache
  src/About/About.test.js
  src/App/App.test.js
  src/Banner/Banner.test.js
  src/Banner/Banner.tsx
  src/BannerIcons/BannerIcons.test.js
  src/BannerIcons/BannerIcons.tsx
  src/Contact/Contact.test.js
  src/Footer/Footer.test.js
  src/Footer/Footer.tsx
  src/Location/Location.test.js
  src/MainNav/MainNav.test.js
  src/NavSearch/NavSearch.test.js
  src/ParkBtn/ParkBtn.test.js
  src/ParkBtn/ParkBtn.tsx
  src/ParkContainer/ParkContainer.test.js
  src/ParkData.js
  src/ParkInfo/ParkInfo.test.js
  src/ParkList/ParkList.test.js
  src/SavedCard/SavedCard.test.js
  src/SavedCard/SavedCard.tsx
  src/SavedParks/SavedParks.test.js
  src/UserNav/UserNav.test.js
  src/samplePark.js
Labels: TDD

#53 Feature/state dropdown
  .eslintcache
  src/MainNav/MainNav.tsx
  src/NavSearch/NavSearch.test.js
  src/NavSearch/NavSearch.tsx
  src/ParkData.js
  src/StateDropdown/StateDropdown.scss
  src/StateDropdown/StateDropdown.test.js
  src/StateDropdown/StateDropdown.tsx
Labels: feature

#54 Feature: Style Cleanup
  .eslintcache
  public/index.html
  src/About/About.scss
  src/App/App.scss
  src/App/App.tsx
  src/Banner/Banner.scss
  src/Banner/Banner.tsx
  src/BannerIcons/BannerIcons.scss
  src/Contact/Contact.scss
  src/Contact/Contact.tsx
  src/Footer/Footer.scss
  src/Footer/Footer.tsx
  src/Location/Location.scss
  src/Location/Location.tsx
  src/MainNav/MainNav.scss
  src/NavSearch/NavSearch.scss
  src/ParkBtn/ParkBtn.scss
  src/ParkBtn/ParkBtn.tsx
  src/ParkContainer/ParkContainer.scss
  src/ParkContainer/ParkContainer.tsx
  src/ParkInfo/ParkInfo.scss
  src/ParkList/ParkList.scss
  src/SavedCard/SavedCard.scss
  src/SavedParks/SavedParks.scss
  src/SavedParks/SavedParks.tsx
  src/UserNav/UserNav.scss
  src/index.scss
  src/mixins.scss
  src/variables.scss
Labels: busy work, cleanup

#55 Cleanup/state dropdown
  .eslintcache
  package-lock.json
  src/Banner/Banner.scss
  src/MainNav/MainNav.test.js
  src/NavSearch/NavSearch.scss
  src/NavSearch/NavSearch.test.js
  src/NavSearch/NavSearch.tsx
  src/StateDropdown/StateDropdown.scss
  src/StateDropdown/StateDropdown.test.js
  src/StateDropdown/StateDropdown.tsx
Labels: TDD, busy work, cleanup

#56 Hotfix - Saved List Bug
  .eslintcache
  src/ParkContainer/ParkContainer.tsx
  src/SavedCard/SavedCard.tsx
  src/SavedParks/SavedParks.tsx
Labels: bug

#60 Fix/local storage
  .eslintcache
  public/manifest.json
  src/App/App.test.js
  src/App/App.tsx
  src/Banner/Banner.tsx
  src/BannerIcons/BannerIcons.tsx
  src/Contact/Contact.tsx
  src/Location/Location.tsx
  src/ParkBtn/ParkBtn.tsx
Labels: bug
